export const ALL_TODO_REQUEST = "ALL_TODO_REQUEST";
export const ALL_TODO_SUCCESS= "ALL_TODO_SUCCESS";
export const ALL_TODO_FAIL= "ALL_TODO_FAIL";

export const TODO_EDIT_REQUEST= "TODO_EDIT_REQUEST";
export const TODO_EDIT_SUCCESS= "TODO_EDIT_SUCCESS";
export const TODO_EDIT_FAIL= "TODO_EDIT_FAIL";


export const TODO_DELETE_REQUEST= "TODO_DELETE_REQUEST";
export const TODO_DELETE_SUCCESS= "TODO_DELETE_SUCCESS";
export const TODO_DELETE_FAIL= "TODO_DELETE_FAIL";